# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3193cb78cde3b8a46e99a3f283816b18bd16fcd10db887198d1dab6ead1d229dcc7ab571216cf772f704ba560cf6e76a3aed88446827228027569eb4ef65ac73

test:
  secret_key_base: 39cdcab201bf7610e9e79ee327235a8d91e4ef15c1d3e302628ed434f848720cd4f7a28cca6905f105b940847d25561d6dbe6011540acd79b74b3f58f2eae082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
